version: '3.8'

services:

  db1:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data/db1:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
    - ${DB_PORT}:5432
    restart: always

  db1-gui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${DBA_PASS}
      - PGADMIN_DEFAULT_EMAIL=${DBA_USER}
      - PGADMIN_PORT=80
    ports:
      - ${DBA_PORT}:80
    depends_on:
      - db1
    restart: always

  db2:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB2_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB2_PASS}
    volumes:
      - ./db/data/db2:/data/db
    ports:
      - ${DB2_PORT}:27017
    restart: always

  db2-gui:
    image: mongo-express
    ports:
      - ${DBA2_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB2_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB2_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB2_USER}:${DB2_PASS}@${DB2_HOST}:${DB2_PORT}/
    depends_on:
      - db2
    restart: always

  api:
    build: .
    env_file:
      - .env
    ports:
      - ${API_PORT}:80
    depends_on:
      - db1
      - db2
    restart: always

  doc:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON_URL=${API_URL}/docs
    ports:
      - ${DOC_PORT}:8080
    depends_on:
      - api
    restart: always
